const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=[window.OC.filePath('photos', '', 'js/LocationMap-C1_Tp6_a.chunk.mjs'),window.OC.filePath('photos', '', 'js/leaflet-5Kx7tT0I.chunk.mjs'),window.OC.filePath('photos', '', 'js/dav-BFHOt1TP.chunk.mjs'),window.OC.filePath('photos', '', 'css/leaflet-lDzrbhio.chunk.css'),window.OC.filePath('photos', '', 'js/icons-BogBEt5I.chunk.mjs'),window.OC.filePath('photos', '', 'css/LocationMap-B-bnlzDm.chunk.css')])))=>i.map(i=>d[i]);
import{d as c,l as n,y as p,z as _,k as m,o as v,t as u}from"./dav-BFHOt1TP.chunk.mjs";import{n as r,y as h,_ as f}from"./index-DozLdMXN.chunk.mjs";import{N as g}from"./PhotosFiltersInput-BxwLLS2e.chunk.mjs";import{N as y}from"./NcLoadingIcon-CiY5sPsQ.chunk.mjs";import{g as x,a as N,f as w,b as C}from"./exif-D4vtjSqK.chunk.mjs";import{n as b}from"./icons-BogBEt5I.chunk.mjs";const P=`<svg
	xmlns="http://www.w3.org/2000/svg"
	viewBox="0 0 24 12">
	<path d="M17,1H7A5,5 0 0,0 2,6 5,5 0 0,0 7,11H17A5,5 0 0,0 22,6 5,5 0 0,0 17,1Z" />
	<circle
		cy="6"
		r="3"
		fill="var(--color-main-background)" />
</svg>`,S=c({__name:"NcIconToggleSwitch",props:{checked:{type:Boolean},size:{default:34},inline:{type:Boolean,default:!1}},setup(t){const o=t;p((s,l)=>({"2d1b8583":l.color,"78386a55":l.cx}));const a=n(()=>o.checked?"var(--color-primary-element)":"var(--color-text-maxcontrast)"),e=n(()=>o.checked?"calc(17 / 24 * 100%)":"calc(7 / 24 * 100%)");return{__sfc:!0,svg:P,props:o,color:a,cx:e,NcIconSvgWrapper:h}}}),k="_iconToggleSwitch_rwBqv",E={"material-design-icon":"_material-design-icon_584lD",iconToggleSwitch:k};var I=function(){var t=this,o=t._self._c,a=t._self._setupProxy;return o(a.NcIconSvgWrapper,{class:t.$style.iconToggleSwitch,attrs:{svg:a.svg,size:t.size,inline:t.inline}})},L=[];const i={$style:E};function T(t){for(var o in i)this[o]=i[o]}var z=r(S,I,L,!1,T,null);const G=z.exports,D={name:"NcVNodes",props:{vnodes:{type:[Array,Object],default:null}},render(){return this.vnodes||this.$slots?.default||this.$scopedSlots?.default?.()}},A=null,B=null;var M=r(D,A,B,!1,null,null);const J=M.exports,$=c({__name:"PhotoMetadataDialog",props:{photo:null},emits:["close"],setup(t,{emit:o}){const a=t,e=_(()=>f(()=>import("./LocationMap-C1_Tp6_a.chunk.mjs"),__vite__mapDeps([0,1,2,3,4,5]),import.meta.url)),s=m(),l=n(()=>s.value===void 0?void 0:x(s.value)),d=n(()=>s.value===void 0?null:N(s.value.gps));return v(async()=>{s.value=await w(a.photo)}),{__sfc:!0,props:a,emit:o,LocationMap:e,metadata:s,exifEntries:l,location:d,t:u,NcDialog:g,NcLoadingIcon:y,formatCoordinates:C}}});var H=function(){var t=this,o=t._self._c,a=t._self._setupProxy;return o(a.NcDialog,{attrs:{name:a.t("photos","Photo metadata")},on:{"update:open":function(e){return a.emit("close")}}},[a.exifEntries===void 0?o(a.NcLoadingIcon,{staticClass:"photo-metadata__loading",attrs:{size:32}}):[o("dl",{staticClass:"photo-metadata"},[o("div",{staticClass:"photo-metadata__entry"},[o("dt",[t._v(t._s(a.t("photos","Filename")))]),o("dd",[t._v(t._s(t.photo.basename))])]),t._l(a.exifEntries,function(e){return o("div",{key:e.label,staticClass:"photo-metadata__entry"},[o("dt",[t._v(t._s(e.label))]),o("dd",[t._v(t._s(e.value))])])}),a.metadata?.place?o("div",{staticClass:"photo-metadata__entry"},[o("dt",[t._v(t._s(a.t("photos","Place")))]),o("dd",[t._v(t._s(a.metadata.place))])]):t._e(),a.location!==null?o("div",{staticClass:"photo-metadata__entry"},[o("dt",[t._v(t._s(a.t("photos","Location")))]),o("dd",[t._v(t._s(a.formatCoordinates(a.location)))])]):t._e()],2),a.location!==null?o("div",{staticClass:"photo-metadata__map"},[o(a.LocationMap,{attrs:{latitude:a.location.latitude,longitude:a.location.longitude,name:a.metadata?.place||t.photo.basename}})],1):t._e(),a.exifEntries.length===0&&a.location===null?o("p",{staticClass:"photo-metadata__empty"},[t._v(" "+t._s(a.t("photos","This photo carries no camera metadata."))+" ")]):t._e()]],2)},O=[],V=b($,H,O,!1,null,"9c2c7a6c");const K=V.exports;export{J as N,K as P,G as a};
//# sourceMappingURL=PhotoMetadataDialog-eSVjesvu.chunk.mjs.map
